program: main.py
method: grid
parameters:
  data:
    values:
      - 'AMCCTP'
  epochs:
    values:
      - 25
  sd:
    values:
      - 4
  lr:
    values:
      - 1e-2
      - 1e-3
      - 1e-4
  lw_res:
    values:
      - 25
command:
  - ${env}
  - python
  - ${program}
  - configs\amc.json