program: main.py
method: grid
parameters:
  data:
    values:
      - 'AMCCTP'
  epochs:
    values:
      - 100
  sd:
    values:
      - 4
  lr:
    values:
      - 1e-2
  lw_res:
    values:
      - 50
command:
  - ${env}
  - python
  - ${program}
  - configs\amc.json