command:
  - ${env}
  - python
  - ${program}
  - configs\config.json
method: grid
parameters:
  cbv_ml:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
  epochs:
    values:
      - 1000
  lr:
    values:
      - 0.01
  lw_res:
    values:
      - 25
  sd:
    values:
      - 0
  undersampling:
    values:
      - 0
program: main.py