program: main.py
method: grid
parameters:
  sd:
    values:
      - 3
  cbv_ml:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
command:
  - ${env}
  - python
  - ${program}
  - configs\config.json