program: main.py
method: grid
parameters:
  lr:
    values:
      - 1e-2
  seed:
    values:
      - 1
  sd:
    values:
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
command:
  - ${env}
  - python
  - ${program}
  - configs\config.json