program: main_st.py
method: grid
parameters:
  sd:
    values:
      - 2
  cbv_ml:
    values:
      - 5
  milestone:
    values:
      - 1000
      - 100
      - 50
  undersampling:
    values:
      - 0.0
  ode_net_type:
    values:
      - 'MLP_tanh'
command:
  - ${env}
  - python
  - ${program}
  - configs\spatiotemporal.json