program: main.py
method: grid
parameters:
  batch_size:
    values:
      - 32
  baseline_zero:
    values:
      - true
      - false
command:
  - ${env}
  - python
  - ${program}
  - configs\config.json