program: main.py
method: grid
parameters:
  cbv_ml:
    values:
      - 5
      - 1
      - 2
      - 3
      - 4
  drop_edges:
    values:
      - true
      - false
  drop_unphysical:
    values:
      - false
      - true
command:
  - ${env}
  - python
  - ${program}
  - configs\config.json