program: main_st.py
method: grid
parameters:
  siren:
    values:
      - true
  siren_w0:
    values:
      - 30
  filter_type:
    values:
      - false
  hidden_tissue:
    values:
      - 128
  hidden_ode:
    values:
      - 64
  temporal_smoothing:
    values:
      - false
  lr:
    values:
      - 1e-3
  init_from_previous_slice:
    values:
      - true
  sd:
    values:
      - 0
  epochs:
    values:
      - 100
  gamma:
    values:
      - 0.5
  use_scheduler:
    values:
      - true
  lw_res:
    values:
      - 1
  batch_size:
    values:
      - 5000
command:
  - ${env}
  - python
  - ${program}
  - configs\spatiotemporal_amc.json