program: main.py
method: grid
parameters:
  sd:
    values:
      - 2
  cbv_ml:
    values:
      - 5
      - 4
      - 3
      - 2
      - 1
  undersampling:
    values:
      - 0.5
      - 0.0
  epochs:
    values:
      - 1000
  lr:
    values:
      - 1e-2
  lw_res:
    values:
      - 25
command:
  - ${env}
  - python
  - ${program}
  - configs\config.json