program: main_st.py
method: grid
parameters:
  siren:
    values:
      - true
  siren_w0:
    values:
      - 30
  hidden_tissue:
    values:
      - 256
  lr:
    values:
      - 5e-3
  init_from_previous_slice:
    values:
      - true
  sd:
    values:
      - 4
  epochs:
    values:
      - 100
  gamma:
    values:
      - 1
  use_scheduler:
    values:
      - true
      - false
  lw_res:
    values:
      - 1
  batch_size:
    values:
      - 5000
command:
  - ${env}
  - python
  - ${program}
  - configs\spatiotemporal_amc.json