program: main_st.py
method: grid
parameters:
  siren:
    values:
      - true
  hidden_tissue:
    values:
      - 32
  epochs:
    values:
      - 300
command:
  - ${env}
  - python
  - ${program}
  - configs\spatiotemporal_amc.json